# Generated by Django 2.0.4 on 2018-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180510_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='item_info',
            name='serial_num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
