# Generated by Django 2.0.4 on 2018-05-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry', '0002_auto_20180515_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
