# Generated by Django 2.0.4 on 2018-05-10 05:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='camera_info',
            fields=[
                ('num', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cart_info',
            fields=[
                ('num', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='coupon_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_num', models.PositiveIntegerField()),
                ('discount_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='item_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_date', models.DateField(auto_now_add=True)),
                ('con_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='item_sort_info',
            fields=[
                ('sort', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('inventory', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.item_sort_info')),
            ],
        ),
        migrations.CreateModel(
            name='mv_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('camera_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.camera_info')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info')),
            ],
        ),
        migrations.CreateModel(
            name='pur_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items')),
            ],
        ),
        migrations.CreateModel(
            name='sex_info',
            fields=[
                ('sex', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='item_info',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sex_info'),
        ),
        migrations.AddField(
            model_name='coupon_info',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info'),
        ),
        migrations.AddField(
            model_name='coupon_info',
            name='items_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items'),
        ),
        migrations.AddField(
            model_name='cart_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info'),
        ),
        migrations.AddField(
            model_name='ad_info',
            name='camera_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.camera_info'),
        ),
        migrations.AddField(
            model_name='ad_info',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items'),
        ),
    ]
