# Generated by Django 2.0.4 on 2018-05-10 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_info',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
