# Generated by Django 2.0.4 on 2018-05-10 08:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180510_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_item_info',
            fields=[
                ('serial_num', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='coupon_sort_info',
            fields=[
                ('serial_num', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='coupons_item',
            fields=[
                ('name', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('discount_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('inventory', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='coupons_sort',
            fields=[
                ('name', models.CharField(default=0, max_length=15, primary_key=True, serialize=False)),
                ('discount_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('inventory', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon_info',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='coupon_info',
            name='items_info',
        ),
        migrations.RenameField(
            model_name='ad_info',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item_info',
            old_name='items',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='ad_info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mv_history',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pur_history',
            name='id',
        ),
        migrations.AddField(
            model_name='ad_info',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mv_history',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pur_history',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin_info',
            name='id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camera_info',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='serial_num',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item_sort_info',
            name='sort',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sex_info',
            name='sex',
            field=models.CharField(default='', max_length=1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='coupon_info',
        ),
        migrations.AddField(
            model_name='coupons_sort',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.item_sort_info'),
        ),
        migrations.AddField(
            model_name='coupons_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items'),
        ),
        migrations.AddField(
            model_name='coupon_sort_info',
            name='coupon_sorts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.coupons_sort'),
        ),
        migrations.AddField(
            model_name='coupon_sort_info',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info'),
        ),
        migrations.AddField(
            model_name='coupon_item_info',
            name='coupon_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.coupons_item'),
        ),
        migrations.AddField(
            model_name='coupon_item_info',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.customer_info'),
        ),
    ]
