# Generated by Django 2.0.4 on 2018-05-18 10:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_auto_20180518_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_sort_info',
            options={'verbose_name_plural': '상품종류'},
        ),
        migrations.AlterField(
            model_name='ad_info',
            name='camera_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Camera_Info', verbose_name='카메라 번호'),
        ),
        migrations.AlterField(
            model_name='ad_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='구매상품'),
        ),
        migrations.AlterField(
            model_name='ad_info',
            name='link_info',
            field=models.CharField(max_length=200, verbose_name='광고영상 링크'),
        ),
        migrations.AlterField(
            model_name='ad_info',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='번호'),
        ),
        migrations.AlterField(
            model_name='camera_info',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False, verbose_name='구매고객'),
        ),
        migrations.AlterField(
            model_name='cart_info',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='카트번호'),
        ),
        migrations.AlterField(
            model_name='cart_info',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Customer_Info', verbose_name='소유자'),
        ),
        migrations.AlterField(
            model_name='coupon_item_info',
            name='coupon_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Coupons_Item', verbose_name='쿠폰이름'),
        ),
        migrations.AlterField(
            model_name='coupon_item_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='소유자'),
        ),
        migrations.AlterField(
            model_name='coupon_item_info',
            name='serial_num',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False, verbose_name='일련번호'),
        ),
        migrations.AlterField(
            model_name='coupon_sort_info',
            name='coupon_sorts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Coupons_Sort', verbose_name='쿠폰이름'),
        ),
        migrations.AlterField(
            model_name='coupon_sort_info',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='소유자'),
        ),
        migrations.AlterField(
            model_name='coupon_sort_info',
            name='serial_num',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False, verbose_name='일련번호'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='할인률'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='inventory',
            field=models.PositiveSmallIntegerField(verbose_name='발매개수'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='쿠폰이 적용된 상품'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='name',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='쿠폰이름'),
        ),
        migrations.AlterField(
            model_name='coupons_item',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='발매일'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='할인률'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='inventory',
            field=models.PositiveSmallIntegerField(verbose_name='발매개수'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='name',
            field=models.CharField(default=0, max_length=15, primary_key=True, serialize=False, verbose_name='쿠폰이름'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='발매일'),
        ),
        migrations.AlterField(
            model_name='coupons_sort',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Item_Sort_Info', verbose_name='쿠폰이 적용된 상품종류'),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='note',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='pwd',
            field=models.CharField(max_length=15, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Sex_Info', verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='inbound_date',
            field=models.DateField(auto_now_add=True, verbose_name='입고일'),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='serial_num',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False, verbose_name='일련번호'),
        ),
        migrations.AlterField(
            model_name='item_sort_info',
            name='sort',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='상품종류'),
        ),
        migrations.AlterField(
            model_name='items',
            name='inventory',
            field=models.PositiveSmallIntegerField(verbose_name='재고'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='items',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Item_Sort_Info', verbose_name='상품종류'),
        ),
        migrations.AlterField(
            model_name='mv_history',
            name='camera_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Camera_Info', verbose_name='카메라 번호'),
        ),
        migrations.AlterField(
            model_name='mv_history',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='이동고객'),
        ),
        migrations.AlterField(
            model_name='mv_history',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='번호'),
        ),
        migrations.AlterField(
            model_name='mv_history',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='이동한 시간'),
        ),
        migrations.AlterField(
            model_name='pur_history',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='구매고객'),
        ),
        migrations.AlterField(
            model_name='pur_history',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='구매상품'),
        ),
        migrations.AlterField(
            model_name='pur_history',
            name='num',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='번호'),
        ),
        migrations.AlterField(
            model_name='pur_history',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='구매시간'),
        ),
        migrations.AlterField(
            model_name='sex_info',
            name='sex',
            field=models.CharField(default='', max_length=1, primary_key=True, serialize=False, verbose_name='성별'),
        ),
    ]
