# Generated by Django 2.0.5 on 2018-05-28 11:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Info',
            fields=[
                ('num', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='번호')),
                ('link_info', models.CharField(max_length=200, verbose_name='광고영상 링크')),
            ],
            options={
                'verbose_name': '광고',
                'verbose_name_plural': '광고',
            },
        ),
        migrations.CreateModel(
            name='Camera_Info',
            fields=[
                ('num', models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False, verbose_name='추가할 카메라수')),
            ],
            options={
                'verbose_name': '카메라',
                'verbose_name_plural': '카메라',
            },
        ),
        migrations.CreateModel(
            name='Cart_Info',
            fields=[
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='추가할 카트수')),
                ('serial_num', models.PositiveIntegerField(default=uuid.uuid1, editable=False, unique=True, verbose_name='일련번호')),
            ],
            options={
                'verbose_name': '카트',
                'verbose_name_plural': '카트',
            },
        ),
        migrations.CreateModel(
            name='Coupon_Item_Info',
            fields=[
                ('serial_num', models.PositiveIntegerField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='일련번호')),
                ('coupon_use', models.BooleanField(default=False, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '상품 쿠폰 재고',
                'verbose_name_plural': '상품 쿠폰 재고',
            },
        ),
        migrations.CreateModel(
            name='Coupons_Item',
            fields=[
                ('name', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='쿠폰이름')),
                ('discount_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='할인률')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='종료일')),
                ('inventory', models.PositiveSmallIntegerField(verbose_name='발매개수')),
            ],
            options={
                'verbose_name': '상품 쿠폰',
                'verbose_name_plural': '상품 쿠폰',
            },
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('id', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='아이디')),
                ('pwd', models.CharField(max_length=15, verbose_name='비밀번호')),
                ('age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='나이')),
                ('note', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '고객정보',
                'verbose_name_plural': '고객정보',
            },
        ),
        migrations.CreateModel(
            name='Item_Info',
            fields=[
                ('serial_num', models.PositiveIntegerField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='일련번호')),
                ('inbound_date', models.DateField(default=datetime.date.today, verbose_name='입고일')),
                ('expire_date', models.DateField(default=datetime.date.today, verbose_name='유통기한')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='입고량')),
                ('pur_use', models.BooleanField(default=False, verbose_name='구매여부')),
            ],
            options={
                'verbose_name': '상품 재고',
                'verbose_name_plural': '상품 재고',
            },
        ),
        migrations.CreateModel(
            name='Item_Sort_Info',
            fields=[
                ('sort', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='상품종류')),
            ],
            options={
                'verbose_name': '상품종류',
                'verbose_name_plural': '상품종류',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('name', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='상품명')),
                ('inventory', models.PositiveSmallIntegerField(default=0, verbose_name='재고')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Item_Sort_Info', verbose_name='상품종류')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('name', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='구획명')),
                ('start_x', models.PositiveIntegerField(default=0, verbose_name='x 시작')),
                ('start_y', models.PositiveIntegerField(default=0, verbose_name='y 시작')),
                ('end_x', models.PositiveIntegerField(default=0, verbose_name='x 끝')),
                ('end_y', models.PositiveIntegerField(default=0, verbose_name='y 끝')),
            ],
            options={
                'verbose_name': '마트 구획',
                'verbose_name_plural': '마트 구획',
            },
        ),
        migrations.CreateModel(
            name='Mv_History',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='이동한 시간')),
                ('x', models.PositiveIntegerField(default=0, verbose_name='x 좌표')),
                ('y', models.PositiveIntegerField(default=0, verbose_name='y 좌표')),
                ('camera_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Camera_Info', verbose_name='카메라 번호')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='이동고객')),
            ],
            options={
                'verbose_name': '고객 이동정보',
                'verbose_name_plural': '고객 이동정보',
            },
        ),
        migrations.CreateModel(
            name='Pur_History',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='구매시간')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='구매고객')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Item_Info', verbose_name='구매상품')),
            ],
            options={
                'verbose_name': '고객 구매정보',
                'verbose_name_plural': '고객 구매정보',
            },
        ),
        migrations.CreateModel(
            name='Sex_Info',
            fields=[
                ('sex', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='성별')),
            ],
            options={
                'verbose_name': '성별',
                'verbose_name_plural': '성별',
            },
        ),
        migrations.AddField(
            model_name='item_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='customer_info',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Sex_Info', verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='coupons_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='쿠폰이 적용된 상품'),
        ),
        migrations.AddField(
            model_name='coupon_item_info',
            name='coupon_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Coupons_Item', verbose_name='쿠폰이름'),
        ),
        migrations.AddField(
            model_name='coupon_item_info',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Customer_Info', verbose_name='소유자'),
        ),
        migrations.AddField(
            model_name='cart_info',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Customer_Info', verbose_name='소유자'),
        ),
        migrations.AddField(
            model_name='ad_info',
            name='camera_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Camera_Info', verbose_name='카메라 번호'),
        ),
        migrations.AddField(
            model_name='ad_info',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Items', verbose_name='구매상품'),
        ),
    ]
