# Generated by Django 2.0.4 on 2018-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180510_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
