# Generated by Django 2.0.4 on 2018-05-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180510_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_info',
            old_name='con_num',
            new_name='serial_num',
        ),
        migrations.AlterField(
            model_name='pur_history',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.item_info'),
        ),
    ]
